// Generated by scripts/export-resources.py; original DE440s coefficients.
enum KernelResource {
    static let name = "moon-1850-2149"
    static let sha256 = "95a58477306cbe6c7ccd7b6691e8440ab5e58b654e9352e17581cb14f06433d8"
    static let start = -54786.5
    static let end = 54786.5
}
