#!/usr/bin/env python3
"""Export pinned, validated lunar sources/kernel and an offline IERS snapshot.

Run with the prototype Python environment and SKYKIT_CACHE. Refreshing the EOP
snapshot is an explicit source-data update: review its SHA and Bulletin C first.
"""
import argparse
from datetime import datetime, timezone
import json
import math
import struct
from jplephem.spk import SPK
from pathlib import Path
import re
import shutil
import sys

import erfa
import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO/'prototypes/ephemeris'))
from prepare import CACHE, ROOT, INPUTS, sha256, verify_build

FINALS_SHA256 = 'c672540e026d3cd4840c0858d4ce2bc4a18c3bc9751f9636c3285e11950d58a1'


def export_kernel(resources):
    source = CACHE / 'de440s.bsp'
    if sha256(source) != INPUTS['de440s.bsp'][1]:
        raise RuntimeError('Unreviewed DE440s source')
    start, end = -54786.5, 54786.5  # 1850-01-01 <= TDB < 2150-01-01
    output = resources / 'moon-1850-2149.bin'
    manifest = dict(format='LUNAR001 little endian', startTDBDaysSinceJ2000=start,
                    endTDBDaysSinceJ2000Exclusive=end, segments=[],
                    source=INPUTS['de440s.bsp'][0], sourceSHA256=INPUTS['de440s.bsp'][1])
    kernel = SPK.open(str(source))
    with output.open('wb') as out:
        out.write(struct.pack('<8sIdd', b'LUNAR001', 4, start, end))
        for center, body in [(0, 3), (0, 10), (3, 399), (3, 301)]:
            segment = kernel[center, body]
            assert segment.data_type == 2
            epoch, interval, coefficients = segment.load_array()
            epoch -= 2451545.0
            first = math.floor((start - 2 - epoch) / interval)
            last = math.ceil((end + 2 - epoch) / interval)
            assert 0 <= first < last <= coefficients.shape[1]
            data = np.asarray(coefficients[:, first:last, :].transpose(1, 0, 2), dtype='<f8')
            count, _, terms = data.shape
            out.write(struct.pack('<IIddII', center, body, epoch + first * interval,
                                  interval, count, terms))
            out.write(data.tobytes())
            manifest['segments'].append(dict(center=center, body=body, records=count,
                                            terms=terms, bytes=data.nbytes))
    kernel.close()
    manifest.update(bytes=output.stat().st_size, sha256=sha256(output))
    (resources.parent / 'KernelResource.swift').write_text(
        '// Generated by scripts/export-resources.py; original DE440s coefficients.\n'
        'enum KernelResource {\n'
        '    static let name = "moon-1850-2149"\n'
        f'    static let sha256 = "{manifest["sha256"]}"\n'
        f'    static let start = {start}\n    static let end = {end}\n' + '}\n')
    return manifest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--finals', type=Path, required=True)
    # A consuming app that links ERFA must ship the notice too. Pass its copy's
    # path to refresh both in one run; skipped when the app repo is not at hand.
    parser.add_argument('--app-license', type=Path, default=None)
    args = parser.parse_args()
    if sha256(args.finals) != FINALS_SHA256:
        raise RuntimeError('Unreviewed finals2000A snapshot')
    build = json.loads((CACHE/'build-manifest.json').read_text()); verify_build(build)
    package = REPO
    native = package/'Sources/NativeSky'
    resources = package/'Sources/SkyKit/Resources'
    for p in [native/'include',native/'erfa',resources]:p.mkdir(parents=True,exist_ok=True)
    copies=[(ROOT/'native/lunar.cpp',native/'lunar.cpp'),(ROOT/'native/lunar.h',native/'include/lunar.h'),
        (CACHE/'erfa-2.0.1/LICENSE',package/'ERFA-LICENSE.txt')]
    if args.app_license:copies.append((CACHE/'erfa-2.0.1/LICENSE',args.app_license))
    for src,dst in copies:shutil.copyfile(src,dst)
    kernel_manifest = export_kernel(resources)
    (resources/'moon-2000-2050.bin').unlink(missing_ok=True)
    required=set();source=CACHE/'erfa-2.0.1/src'
    def visit(name):
        if name in required:return
        required.add(name)
        for symbol in re.findall(r'\bera([A-Z]\w*)\s*\(', (source/(name+'.c')).read_text()):visit(symbol.lower())
    for name in build['builds'][0]['erfaSourceSHA256']:
        if name.endswith('.c'):visit(Path(name).stem)
    visit('dtdb')
    for p in [source/(name+'.c') for name in sorted(required)]+list(source.glob('*.h')):
        shutil.copyfile(p,native/'erfa'/p.name)
    rows=[];last_observed=None
    for line in args.finals.read_text().splitlines():
        if not line[58:68].strip() or not line[18:27].strip():continue
        mjd=float(line[7:15])
        year=int(line[:2])+(1900 if mjd<51544 else 2000)
        dat=float(erfa.dat(year,int(line[2:4]),int(line[4:6]),0.))
        tt=mjd+(dat+32.184)/86400
        offsets=bool(line[97:106].strip() and line[116:125].strip())
        dx=dy=0.
        if offsets:
            x0,y0,_=erfa.xys00a(2400000.5,tt);x6,y6,_=erfa.xys06a(2400000.5,tt)
            dx=float(line[97:106])*np.pi/648000000 + x0-x6
            dy=float(line[116:125])*np.pi/648000000 + y0-y6
        predicted=line[16]=='P' or line[57]=='P'
        if not predicted:last_observed=mjd
        # Interpolate UT1-TAI (continuous), NEVER DUT1 across leap seconds.
        rows.append([mjd,float(line[18:27])*np.pi/648000,float(line[37:46])*np.pi/648000,
            float(line[58:68])-dat,dx,dy,1 if predicted else 0,
            (2 if line[95]=='P' else 1) if offsets else 0])
    assert len(rows)>10000 and all(b[0]-a[0]==1 for a,b in zip(rows,rows[1:]))
    # Export ERFA's immutable UTC history, including 1960–1971 linear drift.
    # Store offset AT the entry date (not the pre-drift coefficient in dat.c).
    leaps=[]
    for entry in erfa.leap_seconds.get():
        year,month=int(entry['year']),int(entry['month'])
        dat=float(erfa.dat(year,month,1,0.))
        rate=round((float(erfa.dat(year,month,1,0.5))-dat)*2, 10)
        leaps.append([datetime(year,month,1,tzinfo=timezone.utc).timestamp(),dat,rate])
    payload=dict(schema=2,source='https://maia.usno.navy.mil/ser7/finals2000A.all',sourceSHA256=FINALS_SHA256,
        lastObservedMJD=last_observed,rows=rows,leaps=leaps,
        leapSecondsConfirmedBefore=datetime(2027,7,1,tzinfo=timezone.utc).timestamp(),
        leapBulletin='IERS Bulletin C 72, 2026-07-06: no leap second at end of December 2026',
        leapBulletinURL='https://hpiers.obspm.fr/iers/bul/bulc/bulletinc.72')
    (resources/'earth-orientation.json').write_text(json.dumps(payload,separators=(',',':'),allow_nan=False)+'\n')
    provenance=dict(kernel=kernel_manifest,erfaVersion='2.0.1',erfaArchiveSHA256=build['inputs']['erfa.tar.gz'][1],
        nativePrototypeSHA256={str(p.relative_to(ROOT)):sha256(p) for p in [ROOT/'native/lunar.cpp',ROOT/'native/lunar.h']},
        eop=dict(source=payload['source'],sha256=FINALS_SHA256,startMJD=rows[0][0],endMJD=rows[-1][0],lastObservedMJD=last_observed),
        fileSHA256={str(p.relative_to(package)):sha256(p) for p in sorted(native.rglob('*')) if p.is_file()})
    provenance['fileSHA256'].update({str(p.relative_to(package)):sha256(p) for p in resources.iterdir() if p.is_file()})
    (package/'provenance.json').write_text(json.dumps(provenance,indent=2)+'\n')
    print('Exported',len(rows),'EOP days;',len(required),'ERFA sources; data end MJD',rows[-1][0])


if __name__=='__main__':main()
